[package]
name = "clubberai_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.5.0"
near-sdk-contract-tools = "3.0.2"
borsh = "1.5.1"
borsh-derive = "1.5.1"